class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '雑種・不明' },
    { id: 3, name: 'シャム' },
    { id: 4, name: 'ブリティッシュショートヘア' },
    { id: 5, name: 'メインクーン' },
    { id: 6, name: 'ペルシャ' },
    { id: 7, name: 'ラグドール' },
    { id: 8, name: 'スフィンクス' },
    { id: 9, name: 'アメリカンショートヘア' },
    { id: 10, name: 'バーミーズ' },
    { id: 11, name: 'エキゾチックショートヘア' },
    { id: 12, name: 'バーマン' },
    { id: 13, name: 'スコティッシュフォールド' },
    { id: 14, name: 'ボンベイ' },
    { id: 15, name: 'サイベリアン' },
    { id: 16, name: 'ロシアンブルー' },
    { id: 17, name: 'ノルウェージャンフォレストキャット' },
    { id: 18, name: 'デボンレックス' },
    { id: 19, name: 'マンチカン' },
    { id: 20, name: 'アメリカンカール' },
    { id: 21, name: 'アメリカンボブテイル' },
    { id: 22, name: 'バリニーズ' },
    { id: 23, name: 'オリエンタルショートヘア' },
    { id: 24, name: 'シャルトリュー' },
    { id: 25, name: 'ターキッシュアンゴラ' },
    { id: 26, name: 'ジャパニーズボブテイル' },
    { id: 27, name: 'マンクス' },
    { id: 28, name: 'アメリカンワイヤーヘア' },
    { id: 29, name: 'エジプシャンマウ' },
    { id: 30, name: 'コーニッシュレックス' },
    { id: 31, name: 'ラガマフィン' },
    { id: 32, name: 'ソマリ' },
    { id: 33, name: 'ヒマラヤン' },
    { id: 34, name: 'コラット' },
    { id: 35, name: 'シンガプーラ' },
    { id: 36, name: 'オシキャット' },
    { id: 37, name: 'トンキニーズ' },
    { id: 38, name: 'ターキッシュバン' },
    { id: 39, name: 'ブリティッシュロングヘア' },
    { id: 40, name: 'ハバナ' },
    { id: 41, name: 'ラパーマ' },
    { id: 42, name: 'チャウシー' },
    { id: 43, name: 'バーミラ' },
    { id: 44, name: 'スノーシュー' },
    { id: 45, name: 'ライコイ' },
    { id: 46, name: 'トイガー' },
    { id: 47, name: 'カラーポイント・ショートヘアー' },
    { id: 48, name: 'ジャバニーズ' },
    { id: 49, name: 'ソコケ' },
    { id: 50, name: 'オーストラリアンミスト' },
    { id: 51, name: 'カオマニー' }
  ]
  include ActiveHash::Associations
  has_many :cats
end
